# action.yaml
name: 'Notebook Publish Github Action'
description: 'A Github Action that takes a sequence of notebooks and executes, then publishes them in specified folders'
inputs:
  nbworkspace:
    description: 'Notebook workspace'
    required: true
  nbsource:
    description: 'Notebook source files (space delimited files changed in the pull request)'
    required: true
  nbtarget:
    description: 'Notebook target folder name (contains executed notebooks)'
    required: true
    default: 'publish/notebook'
  nbdoc:
    description: 'Notebook target folder name for HTML (contains converted html docs)'
    required: true
    default: 'publish/doc'
  nbcommon:
    description: 'Notebook common dependencies that are expected to be present instead of installed within the notebook'
    required: false
    default: ''
outputs:
  published:
    description: 'list of published output files'
    value: ${{ steps.nbaction.outputs.published }}

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        # caching pip dependencies
        cache: 'pip'
    - name: Update Dependencies and env variables
      working-directory: ${{ github.action_path }}
      run: |
        env
        ls ${{github.workspace}}
        python -m pip install --upgrade pip -r requirements.txt
        echo "NB_WORKSPACE=${{ inputs.nbworkspace }}" >> $GITHUB_ENV
        echo "NB_SOURCES=${{ inputs.nbsource }}" >> $GITHUB_ENV
        echo "NB_TARGET_PATH=${{ inputs.nbtarget }}" >> $GITHUB_ENV
        echo "NB_DOC_PATH=${{ inputs.nbdoc }}" >> $GITHUB_ENV
        ls ${{ inputs.nbworkspace }}
      shell: bash
    - name: Run nbaction
      id: nbaction
      working-directory: ${{ github.action_path }}
      run: python $GITHUB_ACTION_PATH/src/nbaction.py
      shell: bash

