# .github/workflows/test_action.yaml
name: Test nbaction 
on: 
  push:
    paths:
      - '**.ipynb'
jobs:
  build-notebooks:
    runs-on: ubuntu-latest
    name: Test the notebook publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: pr
        uses: tj-actions/changed-files@v35
      - name: Run nbaction
        id: commit
        uses: ./ # replace with aspiringastro/nbaction@v1
        with:
          nbsource: '${{ steps.pr.outputs.all_changed_files }}'
          nbtarget: A'publish/notebooks' # specify destination that is not part of .gitignore in your repo
          nbdoc: 'publish/docs'
          nbcommon: 'numpy pandas matplotlib'
      - name: commit updated files
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Show GitHub Actions logo
          committer_name: Github Actions
          commit: --signoff
